version: 2

jobs:
  install:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v18-dependencies-{{ checksum "package-lock.json" }}
            - v18-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm run lint
            npm run audit
            npm run test
      - save_cache:
          paths:
            - node_modules
          key: v18-dependencies-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  build:
    jobs:
      - install
