version: 2

jobs:
  install:
    docker:
      - image: python:3.10.13-alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm run lint
            npm run audit
            npm run test

workflows:
  version: 2
  build:
    jobs:
      - install
