version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: python:3.10.13
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm run lint
            npm run audit
            npm run test
      - run:
          name: Build and release
          command: |
            export IMAGE_URL=833465769753.dkr.ecr.ca-central-1.amazonaws.com/datajitsu-schema-analyzer
            export FUNCTION_NAME=datajitsu-schema-analyzer
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 833465769753.dkr.ecr.$AWS_REGION.amazonaws.com
            docker build -t $IMAGE_URL .
            docker push $IMAGE_URL
            aws lambda update-function-code --region ca-central-1 --function-name $FUNCTION_NAME --image-uri $IMAGE_URL:latest


workflows:
  version: 2
  build-workflow:
    jobs:
      - build
